### ISSUE TITLE
1.3.0 crash awb generation

### ISSUE THREAD

**Issue by rwkyyy** [sameday-courier/woocommerce-plugin#106]
Upon hitting the generate AWB button, there is a fatal error shown in the screen with the following error logged:

```
PHP message: PHP Fatal error: Uncaught JsonException: Syntax error in /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php:338
Stack trace:
#0 /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(338): json_decode('', true, 512, 4194304)
#1 /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(485): Sameday->postAwb(Array)
#2 /www/xxxyyy_999/public/wp-includes/class-wp-hook.php(307): {closure}('')
#3 /www/xxxyyy_999/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /www/xxxyyy_999/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#5 /www/xxxyyy_999/public/wp-admin/admin-post.php(85): do_action('admin_post_add_...')
#6 {main}
thrown in /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php on line 338" while reading response header from upstream, client: IP, server: domain.tld, request: "POST /wp-admin/admin-post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-xxxyyy.sock:", host: "www.domain.tld:57438", referrer: "https://www.domain.tld/wp-admin/post.php?post=48055&action=edit"
```

**Comment by Soptareanu** [comment]
> Upon hitting the generate AWB button, there is a fatal error shown in the screen with the following error logged:
> 
> ```
> PHP message: PHP Fatal error: Uncaught JsonException: Syntax error in /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php:338
> Stack trace:
> #0 /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(338): json_decode('', true, 512, 4194304)
> #1 /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(485): Sameday->postAwb(Array)
> #2 /www/xxxyyy_999/public/wp-includes/class-wp-hook.php(307): {closure}('')
> #3 /www/xxxyyy_999/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
> #4 /www/xxxyyy_999/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
> #5 /www/xxxyyy_999/public/wp-admin/admin-post.php(85): do_action('admin_post_add_...')
> #6 {main}
> thrown in /www/xxxyyy_999/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php on line 338" while reading response header from upstream, client: IP, server: domain.tld, request: "POST /wp-admin/admin-post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-xxxyyy.sock:", host: "www.domain.tld:57438", referrer: "https://www.domain.tld/wp-admin/post.php?post=48055&action=edit"
> ```

Hello. We're sorry for this edge-case. We maid a fix. Can you please update to our v1.3.1 release and share with us your feedback, if every thing is ok or the situation is still persisting ?!

**Comment by rwkyyy** [comment]
@Soptareanu seems to be working fine now!
