### ISSUE TITLE
Fatal error: Uncaught Error: Cannot access offset of type string on string in ... /wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php on line 260

### ISSUE THREAD

**Issue by iliebostan94** [sameday-courier/woocommerce-plugin#159]
Salutare,

Puteti va rog sa ma ajutati cu urmatoarea problema?

Dupa instalarea si setarea pluginului dvs totul merge bine cu exceptia generarii awb-ului.
Deci, la clicarea butonului "Generate awb" > https://i.imgur.com/Fnv6hGV.png primesc urmatoarea eroare > https://i.imgur.com/YS4Wh4u.png 

Va rog atrageti atentie ca am incercat sa generez fisiere AWB utilizand versiunea 1.6.0 a pluginului SamedayCourier Shipping si versiunea actualizata 1.6.3
Generarea fisierelor AWB nu functioneaza cu niciuna dintre versiuni. 
- In procesul de testare am sters cache din browser si site, am deactivat toate pluginurile aferente de caching dupa care am testat plugin-ul. insa eroarea persista.
- De asemenea am testat pluginul pe un site wordpress curat pe local cu 1 singur plugin - Woocommerce, pe tema default Wordpress.

Care credeti ca ar fi problema?
Multumesc,
Ilie.

**Comment by Soptareanu** [comment]
> Salutare,
> 
> Puteti va rog sa ma ajutati cu urmatoarea problema?
> 
> Dupa instalarea si setarea pluginului dvs totul merge bine cu exceptia generarii awb-ului. Deci, la clicarea butonului "Generate awb" > https://i.imgur.com/Fnv6hGV.png primesc urmatoarea eroare > https://i.imgur.com/YS4Wh4u.png
> 
> Va rog atrageti atentie ca am incercat sa generez fisiere AWB utilizand versiunea 1.6.0 a pluginului SamedayCourier Shipping si versiunea actualizata 1.6.3 Generarea fisierelor AWB nu functioneaza cu niciuna dintre versiuni.
> 
> * In procesul de testare am sters cache din browser si site, am deactivat toate pluginurile aferente de caching dupa care am testat plugin-ul. insa eroarea persista.
> * De asemenea am testat pluginul pe un site wordpress curat pe local cu 1 singur plugin - Woocommerce, pe tema default Wordpress.
> 
> Care credeti ca ar fi problema? Multumesc, Ilie.

Buna ziua,

         Am mai facut un release. Puteti verifica din nou ?

**Comment by iliebostan94** [comment]
Salutare Alex,

Multumesc mult pentru raspuns!

Am testat noul release - 1.7.0  > https://i.imgur.com/yiTB0V3.png 
Insa eroarea este aceeasi > https://i.imgur.com/Et47T2o.png

Cum altfel am putea fixa problema?

**Comment by Soptareanu** [comment]
> Salutare Alex,
> 
> Multumesc mult pentru raspuns!
> 
> Am testat noul release - 1.7.0 > https://i.imgur.com/yiTB0V3.png Insa eroarea este aceeasi > https://i.imgur.com/Et47T2o.png
> 
> Cum altfel am putea fixa problema?

Situatia apare de la un tip de exceptie care nu a fost prinsa si care. Prin urmare a fost aruncata in aplicatie. Lucram la remedierea acestei situatii. Totusi, eroarea in cauza face referire la un status in baza de date a contului de pe care s-a incercat requestul care indica faptul ca respectivul cont figureaza ca si inactiv si blocat la emiterile de awb-uri. Trebuie sa luati legatura cu cei de la departamentul nostru de Sales.

**Comment by iliebostan94** [comment]
Multumesc pentru raspuns Alex,

Ai avut dreptate in privinta contului, 
am contactat departamentul Sales si vom rezolva impreuna cu ei.

Multumesc!
