### ISSUE TITLE
Optiunea de selectare locker (show lockermap) nu apare în pagina de checkout

### ISSUE THREAD

**Issue by Tomitzu** [sameday-courier/woocommerce-plugin#165]
Salut. Am instalat plugin-ul, l-am configurat (user, parola, servicii, etc) dar opțiunea de selectare locker nu-mi apare atunci când selectez livrare la easybox în pagina de checkout. Menționez că folosesc Woocommerce + GeneratePress

**Comment by Tomitzu** [comment]
![1](https://github.com/sameday-courier/woocommerce-plugin/assets/38808759/cc661ede-ec40-4ff1-8f44-fe9000ec22ee)
![2](https://github.com/sameday-courier/woocommerce-plugin/assets/38808759/fc988833-41cb-41e3-82ad-70759c84a7a5)

**Comment by strigoiu13** [comment]
iti spun eu de ce, dezactiveaza blocks la cart/checkout page,edit page si undeva in dreapta parca e, revino la ce era inainte de blocks,plugin-ul asta nu merge cu blocks, nu e compatibil. mi-a luat cateva zile sa ma prind de ce nu apare nimic...

**Comment by Tomitzu** [comment]
mulțumesc pentru răspuns. am verificat și într-adevăr funcționează dacă înlocuiesc blocurile „Finalizare comandă” și „Coș” (din paginile cu același nume) cu scurtcodurile aferente: [woocommerce_checkout] și [woocommerce_cart].
