### ISSUE TITLE
Butonul Show Locker Map nu apare

### ISSUE THREAD

**Issue by AdrianGoG** [sameday-courier/woocommerce-plugin#167]
Salutare! Folosesc ultima versiune de WP 6.4.3, impreuna cu WooCommerce 8.5.2.
Problema este ca nu se afiseaza butonul sub nicio forma in pagina de checkout. Am facut numeroase teste: dezactivare module, schimbare tema, schimbare versiune WP, ceea ce nu am incercat este sa iau o versiune anterioara a WooCommerce-ului. Erori nu exista nici in consola si nici in error_log.php. Poate a mai intampinat cineva aceasta situatie. Multam!

**Comment by raulw** [comment]
Vezi sa nu ai pentru checkout "Checkout Blocks", optiune care vine default de la WooCommerce 8.3 incolo. Cu alte cuvinte, pagina de comanda sa fie pe "sistemul vechi", cu shortcode [woocommerce_checkout]

**Comment by AdrianGoG** [comment]
Asta a fost! Multumesc frumos! :D
