### ISSUE TITLE
Optiunea de livrare la easybox nu apare dupa pragul de Free delivery

### ISSUE THREAD

**Issue by nutcrak** [sameday-courier/woocommerce-plugin#168]
If the free delivery threshold is reached, the locker option (Locker NextDay) no longer appears at checkout. 
The other 24H option appears without displaying the price (ok). 
The services are active and with the same amount as the Price Free option. Is there any solution to this problem?

**Comment by havalex** [comment]
Does the cart quantity exceed the maximum number of items for locker set in module's settings?

**Comment by nutcrak** [comment]
Yep that was it. Sorry i managed to figure this out and forgot i put a question here. Thank you though

**Comment by nutcrak** [comment]
Thanks
