### ISSUE TITLE
Problemă apărută după ultimul update 

### ISSUE THREAD

**Issue by Tomitzu** [sameday-courier/woocommerce-plugin#173]
![sameday easyBox selection - issue](https://github.com/sameday-courier/woocommerce-plugin/assets/38808759/0fda3e4c-7f0c-43ba-ab10-b75365720daa)

Partea de selectare a easyBox ului apare acum deasupra 'woocommerce-checkout-review-order' așa cum puteți observa din screenshot ul atașat - practic are pusee de independență  :))

**Comment by Tomitzu** [comment]
...până una-alta, am dat rollback la versiunea anterioară...

**Comment by Soptareanu** [comment]
> ...până una-alta, am dat rollback la versiunea anterioară...

Am mai lansat o versiune noua.

**Comment by Tomitzu** [comment]
acum am făcut update. problema a fost rezolvată în versiunea 1.7.7
Mulțumesc și o seară plăcută!
