### ISSUE TITLE
`getApiUrl(): string` are și situații în care întoarce alt tip

### ISSUE THREAD

**Issue by iamntz** [sameday-courier/woocommerce-plugin#58]
```
plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php.
Mesaj eroare: Uncaught TypeError: Return value of
SamedayCourierHelperClass::getApiUrl() must be of the type string,
null returned in
```

În cazul de față, autentificarea nu funcționează. Nu știu de ce, pentru că nu dă nici o eroare, nicăieri. Cineva o fi uitat să facă error logging pe undeva 😁 

https://github.com/sameday-courier/woocommerce-plugin/commit/15658c151adcb9580c959d327351fe40d5c159a4#diff-e9f4cefc21ddee64dccfa647506e54b57aacb175c2cf69b7ed823673de51f110R45

**Comment by Soptareanu** [comment]
This issue was fiexed.

**Comment by Soptareanu** [comment]
This issue was fiexed.
