### ISSUE TITLE
Error when load services, pickup points, lockers

### ISSUE THREAD

**Issue by 92mate** [sameday-courier/woocommerce-plugin#62]
I added the login details, but when I try to refresh services, pickup points or lockers, I get a fatal error.
I already tried the very first version of the plugin, but it is also not working on my site. I deactivated all other plugin, changed the theme. 
The country is Hungary, but the plugin shows RO. In ispect elemet i see, both is supported, but both have the RO value.
What can i do?

**Comment by Soptareanu** [comment]
The plugin is not able to be used in Hungarian environment for the moment. This feature will be released very soon. Our development team is working on it.
