### ISSUE TITLE
Eroare la generare AWB în Wordpress 5.9.2  :(

### ISSUE THREAD

**Issue by denisac** [sameday-courier/woocommerce-plugin#79]
A apărut o eroare de tipul E_ERROR pe linia 53 a fișierului /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php. Mesaj eroare: Uncaught TypeError: Return value of SamedayCourierHelperClass::getHostCountry() must be of the type string, null returned in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php:53
Stack trace:
#0 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php(61): SamedayCourierHelperClass::getHostCountry()
#1 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(318): SamedayCourierHelperClass::getApiUrl()
#2 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(489): Sameday->postAwb(Array)
#3 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(307): {closure}('')
#4 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /home3/r72333gent/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /home3/r72333gent/public_html/wp

Buna , 
Am eroarea de mai sus aparuta la generarea de AWB, Wordpress versiune 5.9.2, Same day Version: 1.2.8 . 
Idei cum as putea sa rezolv ?

Multumesc

**Comment by Soptareanu** [comment]
> A apărut o eroare de tipul E_ERROR pe linia 53 a fișierului /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php. Mesaj eroare: Uncaught TypeError: Return value of SamedayCourierHelperClass::getHostCountry() must be of the type string, null returned in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php:53 Stack trace: #0 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php(61): SamedayCourierHelperClass::getHostCountry() #1 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(318): SamedayCourierHelperClass::getApiUrl() #2 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(489): Sameday->postAwb(Array) #3 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(307): {closure}('') #4 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #5 /home3/r72333gent/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #6 /home3/r72333gent/public_html/wp
> 
> Buna , Am eroarea de mai sus aparuta la generarea de AWB, Wordpress versiune 5.9.2, Same day Version: 1.2.8 . Idei cum as putea sa rezolv ?
> 
> Multumesc

Incercam si noi acum sa testam compatibilitatea cu versiunea 5.9.2 si revenim cu un update!

**Comment by denisac** [comment]
Buna , 
Multumesc pentru ca lucrati la asta si temporar am modificat functia de mai jos  :

	public static function getHostCountry(): string
	{
		// The default will always be RO

		//return  (null !== self::getSamedaySettings()['host_country'] || "" !== self::getSamedaySettings()['host_country'])
		//	? self::getSamedaySettings()['host_country']
		//	: self::API_HOST_LOCALE_RO;
		return 'RO';
	}

**Comment by Soptareanu** [comment]
> 

Puteti sa verificati ce anume date vin pe self::getSamedaySettings()['host_country'] sa ne putem da seama mai usor din ce motiv nu se valideaza conditia ? Daca nu aveti xDebug configurat, puteti sa puneti un de exempul un var_dump(self::getSamedaySettings()['host_country']); Ne-ar ajuta foarte mult un feedback.

**Comment by Soptareanu** [comment]
> Buna , Multumesc pentru ca lucrati la asta , pentru a continua sa utiliz pluginul temporar am modificat functia de mai jos :
> 
> ```
> public static function getHostCountry(): string
> {
> 	// The default will always be RO
> 
> 	//return  (null !== self::getSamedaySettings()['host_country'] || "" !== self::getSamedaySettings()['host_country'])
> 	//	? self::getSamedaySettings()['host_country']
> 	//	: self::API_HOST_LOCALE_RO;
> 	return 'RO';
> }
> ```

Am facut un fix. incercati sa faceti un update.

**Comment by denisac** [comment]
Sorry , acum am vazut mesajul .
Cool ! Am facut update si functioneaza normal generarea de AWb . 
Mersi
