### ISSUE TITLE
disable locker default as shipping option

### ISSUE THREAD

**Issue by rwkyyy** [sameday-courier/woocommerce-plugin#85]
Did not found an option to disable the locker as default shipping option, any way to tweak this? 
I want to offer option as locker, not default as locker.

**Comment by Soptareanu** [comment]
> Did not found an option to disable the locker as default shipping option, any way to tweak this? I want to offer option as locker, not default as locker.

There is not a way to set the locker option as a default shipping option.

**Comment by rwkyyy** [comment]
> > Did not found an option to disable the locker as default shipping option, any way to tweak this? I want to offer option as locker, not default as locker.
> 
> There is not a way to set the locker option as a default shipping option.

on two differente instances the locker option is default (besides courier).

**Comment by Soptareanu** [comment]
> > > Did not found an option to disable the locker as default shipping option, any way to tweak this? I want to offer option as locker, not default as locker.
> > 
> > 
> > There is not a way to set the locker option as a default shipping option.
> 
> on two differente instances the locker option is default (besides courier).

What do you mean when you say different instances ?

**Comment by rwkyyy** [comment]
> > > > Did not found an option to disable the locker as default shipping option, any way to tweak this? I want to offer option as locker, not default as locker.
> > > 
> > > 
> > > There is not a way to set the locker option as a default shipping option.
> > 
> > 
> > on two differente instances the locker option is default (besides courier).
> 
> What do you mean when you say different instances ?

instances = websites/configurations

**Comment by Soptareanu** [comment]
> > > > > Did not found an option to disable the locker as default shipping option, any way to tweak this? I want to offer option as locker, not default as locker.
> > > > 
> > > > 
> > > > There is not a way to set the locker option as a default shipping option.
> > > 
> > > 
> > > on two differente instances the locker option is default (besides courier).
> > 
> > 
> > What do you mean when you say different instances ?
> 
> instances = websites/configurations

Now I understand your question, but the answer is no, the plugin are develop to work on an only one instance.

**Comment by rwkyyy** [comment]
No, you did not understand.

EN: I have tested on two different instances (website), on shipping options the default is locker, not courier -- there is no option to change this.
RO: Am testat pe două website-uri diferite, pentru zona de livrare, implicit este locker, nu curier - nu există modalitate de a schimba acest lucru.

**Comment by rwkyyy** [comment]
OK, de dragul clarității:
Am două website-uri în care apare 1. Curier (Sameday) și 2. Locker, ambele vin din integrare, iar implicit este locker-ul bifat; nu se dorește asta, că nu toată lumea vrea locker, majoritatea oamenilor nici nu știu ce este (decât dacă ești din București); nu am găsit o modalitate cum să schimb ca să nu mai fie implicit la locker; acest lucru încerc să rezolv.

**Comment by rwkyyy** [comment]
@Soptareanu aparent problema aceasta apare doar când ai acest snippet activ:
https://woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/#section-4, după ce înlături snippetul se rezolvă problema
